### PR TITLE
WIP: Radio tracking, TFAR, AI chatter, UVG Jamming, EMP optimization

### PR DESCRIPTION
**Pull request by Crowdedlight**
**Radio Tracking**
- [x] Implement so zeus can turn on that TFAR transmissions show up as spectrum signals while radios are used
- [x] Implement radio-chatter module that can be put on AI or objects that randomly broadcast spectrum signals
- [x] Implement so players can listen to the radio-chatter module by "firing" the spectrum device
- [x] Add voice lines as per our document to radio-chatter for players to listen to
- [x] Add morse-code section of sounds
- [x] Add code for selection voice-pack when adding radio-chatter to unit

**Spectrum Device and UVG Jamming**
- [x] Changed so spectrum device change available frequencies based on antennas. 30-389MHz is used for radio tracking, 390-500 Mhz is used for zeus-placed beacons, 433 Jammer, is used for drone/UVG jamming
- [x] Implement UVG / Drone jamming. Each UVG has random signal 433-434 MHz only visible with jammer attachment. (Jamming should be like 300-500m distance or so)
- [x] Implement so firing at UVG at more than -50 strength jams it with a 2-3s initial delay. Play electronic jam-effect sound. 
- [x] If we use distance strength, we should be able to terminate current jam if strength falls below -50 strength?
- [x] Try and change weapon while holding down mouse1, to test what happens?
- [x] If someone else right-click while one is jamming, it would reset the jam. Figure out to track who is jamming and only "enableAI" if none is jamming, instead if only one is stopping? 

**EMP Particle optimization**  

- [x] Lower amount of sparkle sprites and unit/car particle effect
- [x] Consider removing unit/car effect. The ones with small lightning bolts
~~- [ ] Try to change sparks effect to 2D sprite effects instead of current 3D spaceobjects.~~
- [x] Reduce max radius to 2500m. 5k is just too much on frame impact
- [x] Add spawning of "The device" as an optional checkbox and make it work when only given a position

**EMP functionality cross-mods**
- [x] TFAR still show signal source on transmission if EMP'ed and thus disabled. Add checking if radio is disabled for radio-chat local signal handler
- [x] smaller radio-chatter text. Or figure out to make it scale depending on distance?

~~**AI Voice Talk**~~
~~**Add this for future release, missing the voice lines for now**~~

~~- [ ] Make module you can put on player/group with set intervals and voice-line pack which plays the voicelines. Useful to add "talking" to AI to alert to their position or presence on sneaky missions. Using same voice packs as available with radiochatter~~
~~- [ ] always get group from input target as we randomly want to choose different group members to talk~~
~~- [ ] use server-loop like "addSound" to save and run the playing of sounds~~
~~- [ ] Add label to group where its enabled so Zeus can see who is talking~~

**General** 

- [x] addsound should also show as zeus label, so we know where sounds are added
- [x] make it possible for custom missions to disable spectrum device. CBA setting or a simple variable that can be set false before ``postInit`` 
- [x] Make units with signal-sources, or radio-chatter/voice-chatter show a symbol or text for it, for zeus. Only draw if within "some" distance of unit with zeus cam.  
- [x] Fixed bug with jammer not resetting TFAR for players if its the only jammer and is removed by removeJammer module
- [x] Set the position of the zeus-text for each module slightly different so they don't overlap completely if used on same object
- [x] Go through the zeus text, and cut down the length. Some information might not be needed, as it can be seen by reusing module, or its enough to just know what type and that its placed on the unit
- [x] Make the zeus drawText toggleable with a keybind. CBA keybind/setting. Check how playerFPS does?

### CODE REVIEW

**Comment by Crowdedlight** [comment]
**Testing cases**

- [ ] EMP performance, FPS for all with 500m, 1000m, 2500m. (Might change to CBA events instead of remoteExec to see if network traffic is the issue?)
- [ ] Disable of spectrum device for individual players
- [ ] zeus labels only visible for zeus, in zeus view
- [ ] EMP with radioTracking on, will make the radio stop work, but also stop it broadcasting a signal

- [ ] Test different antennas across different users and that they can only see signals within their range
- [ ] Test jamming on UGVs. Can they see the signal, can they jam
- [ ] Test one start jamming, another also starts jamming, the first stops and see it should still be jammed
- [ ] Test that if one is jamming another can't start and stop jamming 
- [ ] Test aggro. If jammed before aggro and someone walks close past it, will it aggro when jamming stops. 
- [ ] Test what happens if listening to a UGV without the jammer antenna on

- [ ] Test that TFAR signals are broadcast for players to see when turned on. 
- [ ] Test radio chatter module works as expected
- [ ] Test the voicepacks/lines on the radio chatter module
- [ ] Test adding the morse/electronic sounds to object, not unit

**Comment by Crowdedlight** [comment]
**Final Prep**

- [ ] add Readme features
- [ ] add new stuff to wiki, as this changes quite a bit, make sure to get this on wiki before release
- [ ] search code for "systemChat" and "diag_log" to find all debug code and remove it

**Comment by Crowdedlight** [comment]
**Testing Notes:**

`Cannot find base CBA_Extended_EventHandlers for z\crowsEW\addons\emp\config.bin/CfgVehicles/Crows_Emp_Device/EventHandlers/CBA_Extended_EventHandlers/`

`[CBA] (xeh) WARNING: Crows_Emp_Device does not support Extended Event Handlers! Addon: Crows-Electronic-Warfare`

"re-enabling spectrum device when disabled in settings, and it does not go back to normal "limits" and scroll. Changing antenna resets it correctly"

"Rad suddenly got 000.0 Mhz on handheld no gui, but gui works fine. Even changing selection in gui, doesn't work. See screenshot in discord"

"voice lines in radio chatter is always british no matter what zeus select"

**Comment by Crowdedlight** [comment]
- [ ] why does the jamming add 4-5 instances of the same jammer to the jam array

**Comment by Mrbigdick911** [comment]
> **Radio Tracking**
> - [x] Implement so zeus can turn on that TFAR transmissions show up as spectrum signals while radios are used
> - [x] Implement radio-chatter module that can be put on AI or objects that randomly broadcast spectrum signals
> - [x] Implement so players can listen to the radio-chatter module by "firing" the spectrum device
> - [x] Add voice lines as per our document to radio-chatter for players to listen to
> - [x] Add morse-code section of sounds
> - [x] Add code for selection voice-pack when adding radio-chatter to unit
> 
> **Spectrum Device and UVG Jamming**
> - [x] Changed so spectrum device change available frequencies based on antennas. 30-389MHz is used for radio tracking, 390-500 Mhz is used for zeus-placed beacons, 433 Jammer, is used for drone/UVG jamming
> - [x] Implement UVG / Drone jamming. Each UVG has random signal 433-434 MHz only visible with jammer attachment. (Jamming should be like 300-500m distance or so)
> - [x] Implement so firing at UVG at more than -50 strength jams it with a 2-3s initial delay. Play electronic jam-effect sound. 
> - [x] If we use distance strength, we should be able to terminate current jam if strength falls below -50 strength?
> - [x] Try and change weapon while holding down mouse1, to test what happens?
> - [x] If someone else right-click while one is jamming, it would reset the jam. Figure out to track who is jamming and only "enableAI" if none is jamming, instead if only one is stopping? 
> 
> **EMP Particle optimization**  
> 
> - [x] Lower amount of sparkle sprites and unit/car particle effect
> - [x] Consider removing unit/car effect. The ones with small lightning bolts
> ~~- [ ] Try to change sparks effect to 2D sprite effects instead of current 3D spaceobjects.~~
> - [x] Reduce max radius to 2500m. 5k is just too much on frame impact
> - [x] Add spawning of "The device" as an optional checkbox and make it work when only given a position
> 
> **EMP functionality cross-mods**
> - [x] TFAR still show signal source on transmission if EMP'ed and thus disabled. Add checking if radio is disabled for radio-chat local signal handler
> - [x] smaller radio-chatter text. Or figure out to make it scale depending on distance?
> 
> ~~**AI Voice Talk**~~
> ~~**Add this for future release, missing the voice lines for now**~~
> 
> ~~- [ ] Make module you can put on player/group with set intervals and voice-line pack which plays the voicelines. Useful to add "talking" to AI to alert to their position or presence on sneaky missions. Using same voice packs as available with radiochatter~~
> ~~- [ ] always get group from input target as we randomly want to choose different group members to talk~~
> ~~- [ ] use server-loop like "addSound" to save and run the playing of sounds~~
> ~~- [ ] Add label to group where its enabled so Zeus can see who is talking~~
> 
> **General** 
> 
> - [x] addsound should also show as zeus label, so we know where sounds are added
> - [x] make it possible for custom missions to disable spectrum device. CBA setting or a simple variable that can be set false before ``postInit`` 
> - [x] Make units with signal-sources, or radio-chatter/voice-chatter show a symbol or text for it, for zeus. Only draw if within "some" distance of unit with zeus cam.  
> - [x] Fixed bug with jammer not resetting TFAR for players if its the only jammer and is removed by removeJammer module
> - [x] Set the position of the zeus-text for each module slightly different so they don't overlap completely if used on same object
> - [x] Go through the zeus text, and cut down the length. Some information might not be needed, as it can be seen by reusing module, or its enough to just know what type and that its placed on the unit
> - [x] Make the zeus drawText toggleable with a keybind. CBA keybind/setting. Check how playerFPS does?

**Pull request merged**
